spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};
      databaseName=${DB_NAME};
      encrypt=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: /api

#logging:
#  level:
#    org.flywaydb: DEBUG

